/**
 * MASSIVE NICHE KEYWORD DATABASE
 * 3000+ search queries za Skool Discovery pretragu.
 * Svaki keyword postaje: https://www.skool.com/discovery?q=KEYWORD
 */

const NICHE_KEYWORDS = [
    // ===== BUSINESS & ENTREPRENEURSHIP =====
    "business", "entrepreneurship", "startup", "small business", "online business",
    "business strategy", "business coaching", "business plan", "business model",
    "business development", "business growth", "business automation", "business finance",
    "business management", "business mentor", "business networking", "business scaling",
    "solopreneur", "side hustle", "passive income", "multiple income streams",
    "franchise", "brick and mortar", "local business", "home business",
    "women in business", "young entrepreneur", "serial entrepreneur",
    "bootstrapping", "lean startup", "mvp", "product market fit",
    "business exit", "mergers acquisitions", "venture capital", "angel investing",
    "pitch deck", "fundraising", "investor relations", "business valuation",
    "business operations", "supply chain", "logistics", "procurement",
    "business intelligence", "competitive analysis", "market research",
    "customer acquisition", "customer retention", "customer success",
    "b2b", "b2c", "d2c", "marketplace", "platform business",
    "subscription business", "recurring revenue", "mrr", "arr",
    "business podcast", "business book club", "mastermind group",
    "accountability group", "peer advisory", "ceo group",

    // ===== MARKETING =====
    "marketing", "digital marketing", "content marketing", "email marketing",
    "social media marketing", "influencer marketing", "affiliate marketing",
    "performance marketing", "growth marketing", "brand marketing",
    "marketing strategy", "marketing automation", "marketing analytics",
    "marketing funnel", "sales funnel", "conversion optimization",
    "landing page", "lead generation", "lead magnet", "opt in",
    "facebook ads", "instagram ads", "tiktok ads", "youtube ads",
    "google ads", "ppc", "sem", "paid advertising", "media buying",
    "seo", "search engine optimization", "organic traffic", "keyword research",
    "link building", "local seo", "technical seo", "on page seo",
    "content strategy", "content creation", "blogging", "blog",
    "podcast", "podcasting", "podcast growth", "podcast monetization",
    "video marketing", "viral marketing", "guerrilla marketing",
    "community marketing", "word of mouth", "referral marketing",
    "brand strategy", "brand identity", "brand positioning", "personal brand",
    "pr", "public relations", "media relations", "press release",
    "event marketing", "webinar", "virtual summit", "online event",
    "marketing agency", "marketing consultant", "cmo", "marketing director",
    "marketing for coaches", "marketing for authors", "marketing for musicians",
    "marketing for photographers", "marketing for real estate",
    "marketing for dentists", "marketing for lawyers", "marketing for doctors",
    "direct response marketing", "copywriting", "sales copy", "ad copy",
    "headlines", "hooks", "storytelling", "brand storytelling",
    "email list building", "newsletter", "email sequence", "drip campaign",
    "crm", "hubspot", "salesforce", "activecampaign", "convertkit",
    "clickfunnels", "go high level", "high level", "kajabi", "systeme",
    "MailChimp", "Beehiiv", "substack", "ghost",

    // ===== SALES =====
    "sales", "sales training", "sales coaching", "sales strategy",
    "cold calling", "cold email", "cold outreach", "warm outreach",
    "sales script", "objection handling", "closing", "closing techniques",
    "high ticket sales", "high ticket closing", "consultative selling",
    "solution selling", "value selling", "challenger sale",
    "sales pipeline", "sales process", "sales team", "sales management",
    "inside sales", "outside sales", "field sales", "enterprise sales",
    "saas sales", "software sales", "tech sales", "b2b sales",
    "appointment setting", "prospecting", "qualifying leads",
    "sales presentation", "demo", "product demo", "pitch",
    "negotiation", "deal making", "contract negotiation",
    "sales enablement", "sales operations", "revenue operations",
    "commission", "compensation plan", "sales compensation",

    // ===== AGENCY & FREELANCE =====
    "agency", "marketing agency", "creative agency", "digital agency",
    "smma", "social media management", "social media agency",
    "web design agency", "seo agency", "ppc agency", "ad agency",
    "agency growth", "agency scaling", "agency owner", "agency life",
    "freelance", "freelancing", "freelancer", "gig economy",
    "upwork", "fiverr", "freelance writing", "freelance design",
    "freelance developer", "freelance consultant", "freelance coach",
    "virtual assistant", "va", "online assistant",
    "client acquisition", "client management", "client retention",
    "proposal writing", "pricing strategy", "retainer",
    "white label", "outsourcing", "subcontracting",
    "consulting", "consultant", "management consulting",
    "strategy consulting", "it consulting", "hr consulting",

    // ===== ECOMMERCE & DROPSHIPPING =====
    "ecommerce", "e-commerce", "online store", "shopify",
    "dropshipping", "drop shipping", "dropship", "print on demand",
    "amazon fba", "amazon seller", "amazon private label",
    "ebay", "etsy", "etsy seller", "handmade",
    "woocommerce", "bigcommerce", "magento",
    "product sourcing", "alibaba", "wholesale", "retail arbitrage",
    "inventory management", "fulfillment", "shipping",
    "ecommerce marketing", "ecommerce seo", "product photography",
    "product listing", "conversion rate", "cart abandonment",
    "upsell", "cross sell", "average order value",
    "subscription box", "dtc brand", "private label",
    "ecommerce analytics", "ecommerce automation",
    "tiktok shop", "instagram shop", "facebook marketplace",
    "walmart marketplace", "multichannel selling",

    // ===== REAL ESTATE =====
    "real estate", "real estate investing", "real estate agent",
    "real estate marketing", "real estate coaching",
    "rental property", "rental income", "landlord",
    "property management", "property investing",
    "flipping houses", "house flipping", "fix and flip",
    "wholesale real estate", "wholesaling",
    "commercial real estate", "multifamily", "apartment investing",
    "airbnb", "short term rental", "vacation rental",
    "reit", "real estate syndication", "real estate fund",
    "real estate development", "new construction",
    "mortgage", "mortgage broker", "real estate finance",
    "real estate photography", "real estate videography",
    "real estate lead generation", "realtor", "keller williams",
    "exp realty", "coldwell banker", "remax",
    "land investing", "raw land", "mobile home",
    "storage units", "self storage", "car wash investing",
    "laundromat", "vending machine", "atm business",

    // ===== FINANCE & INVESTING =====
    "finance", "personal finance", "financial literacy",
    "investing", "stock market", "stocks", "stock trading",
    "options trading", "options", "futures trading", "futures",
    "day trading", "swing trading", "position trading",
    "forex", "forex trading", "currency trading",
    "crypto", "cryptocurrency", "bitcoin", "ethereum",
    "defi", "web3", "nft", "blockchain",
    "crypto trading", "crypto investing", "altcoin",
    "index fund", "etf", "mutual fund", "portfolio management",
    "dividend investing", "value investing", "growth investing",
    "retirement planning", "401k", "ira", "roth ira",
    "financial planning", "financial advisor", "wealth management",
    "tax planning", "tax strategy", "tax optimization",
    "accounting", "bookkeeping", "cpa", "financial modeling",
    "budgeting", "saving money", "debt free", "debt payoff",
    "credit score", "credit repair", "credit card rewards",
    "alternative investments", "commodities", "gold investing",
    "angel investing", "private equity", "hedge fund",

    // ===== TRADING =====
    "trading", "trader", "trading strategy", "trading psychology",
    "technical analysis", "chart patterns", "price action",
    "scalping", "algorithmic trading", "bot trading",
    "trading signals", "trading room", "live trading",
    "trading journal", "risk management", "money management",
    "prop firm", "funded trader", "ftmo", "topstep",
    "metatrader", "thinkorswim", "tradingview",
    "ict", "smart money", "order flow", "volume profile",
    "supply demand", "market structure", "fair value gap",
    "fibonacci", "elliott wave", "harmonic patterns",
    "trading mentorship", "trading education", "trading course",

    // ===== COACHING & CONSULTING =====
    "coaching", "life coaching", "business coaching", "executive coaching",
    "health coaching", "wellness coaching", "nutrition coaching",
    "fitness coaching", "mindset coaching", "performance coaching",
    "relationship coaching", "career coaching", "leadership coaching",
    "coaching business", "coaching certification", "icf",
    "coaching tools", "coaching frameworks", "coaching methodology",
    "group coaching", "high ticket coaching", "coaching program",
    "coaching funnel", "coaching offer", "coaching pricing",
    "consulting business", "consulting framework", "consulting proposal",
    "6 figure coaching", "7 figure coaching", "scaling coaching",
    "transformational coaching", "nlp coach", "hypnotherapy",

    // ===== TECH & SOFTWARE =====
    "tech", "technology", "software", "saas",
    "programming", "coding", "web development", "app development",
    "javascript", "python", "react", "node js",
    "html css", "frontend", "backend", "full stack",
    "mobile app", "ios development", "android development",
    "flutter", "react native", "swift", "kotlin",
    "data science", "machine learning", "artificial intelligence", "ai",
    "deep learning", "neural network", "nlp", "computer vision",
    "chatgpt", "openai", "claude", "gemini ai",
    "ai tools", "ai automation", "ai for business", "ai agent",
    "ai prompting", "prompt engineering", "ai workflow",
    "ai art", "ai video", "ai music", "ai writing",
    "midjourney", "dall-e", "stable diffusion", "runway",
    "no code", "low code", "bubble", "webflow", "wordpress",
    "automation", "zapier", "make", "n8n", "process automation",
    "devops", "cloud computing", "aws", "azure", "google cloud",
    "cybersecurity", "information security", "ethical hacking",
    "blockchain development", "smart contract", "solidity",
    "game development", "unity", "unreal engine", "godot",
    "ui ux", "ux design", "ui design", "product design",
    "figma", "adobe xd", "sketch", "design system",
    "data analytics", "sql", "tableau", "power bi",
    "product management", "scrum", "agile", "project management",
    "tech startup", "saas startup", "micro saas", "indie hacker",

    // ===== CONTENT CREATION & SOCIAL MEDIA =====
    "content creator", "content creation", "youtube",
    "youtuber", "youtube growth", "youtube monetization",
    "youtube shorts", "youtube channel", "youtube automation",
    "tiktok", "tiktok growth", "tiktok monetization", "tiktok creator",
    "instagram", "instagram growth", "instagram reels",
    "instagram influencer", "instagram marketing",
    "twitter", "twitter growth", "x growth", "threads",
    "linkedin", "linkedin growth", "linkedin marketing",
    "linkedin content", "linkedin lead generation",
    "pinterest", "pinterest marketing", "pinterest strategy",
    "snapchat", "reddit", "reddit marketing",
    "social media", "social media growth", "social media strategy",
    "social media manager", "social media content",
    "influencer", "micro influencer", "ugc creator",
    "ugc", "user generated content", "brand deals",
    "creator economy", "monetize content", "sponsorship",
    "faceless youtube", "faceless content", "faceless channel",
    "thumbnail design", "video editing", "video production",
    "premiere pro", "final cut pro", "davinci resolve", "capcut",
    "live streaming", "twitch", "kick", "live stream",
    "reels", "short form content", "short form video",
    "viral content", "going viral", "algorithm",
    "community building", "audience building", "fan base",
    "newsletter growth", "email newsletter",

    // ===== PHOTOGRAPHY & VIDEOGRAPHY =====
    "photography", "photographer", "photography business",
    "portrait photography", "wedding photography", "landscape photography",
    "product photography", "food photography", "fashion photography",
    "street photography", "wildlife photography", "sports photography",
    "real estate photography", "drone photography", "aerial photography",
    "newborn photography", "family photography", "boudoir photography",
    "event photography", "concert photography", "travel photography",
    "photography editing", "lightroom", "photoshop", "capture one",
    "photography lighting", "studio lighting", "natural light",
    "photography composition", "photography technique",
    "photography portfolio", "photography marketing",
    "stock photography", "photo licensing", "photography prints",
    "film photography", "analog photography", "35mm",
    "videography", "videographer", "video production",
    "wedding videography", "music video", "commercial video",
    "documentary", "film making", "cinematography", "cinema",
    "drone videography", "fpv drone", "drone pilot",
    "camera gear", "sony", "canon", "nikon", "fujifilm",
    "gimbal", "stabilizer", "lens", "camera settings",
    "color grading", "color correction", "lut",

    // ===== HEALTH & FITNESS =====
    "health", "fitness", "gym", "workout", "exercise",
    "weight loss", "fat loss", "body transformation",
    "muscle building", "bodybuilding", "strength training",
    "powerlifting", "weightlifting", "olympic lifting",
    "crossfit", "hiit", "cardio", "endurance",
    "calisthenics", "bodyweight", "home workout",
    "yoga", "pilates", "barre", "stretching", "flexibility",
    "martial arts", "mma", "boxing", "muay thai", "jiu jitsu",
    "bjj", "karate", "taekwondo", "kickboxing", "self defense",
    "running", "marathon", "triathlon", "cycling", "swimming",
    "hiking", "climbing", "rock climbing", "bouldering",
    "golf", "tennis", "pickleball", "basketball", "soccer",
    "football", "baseball", "volleyball", "hockey", "lacrosse",
    "surfing", "skateboarding", "snowboarding", "skiing",
    "personal trainer", "online coaching", "fitness coach",
    "fitness business", "gym owner", "fitness marketing",
    "nutrition", "meal prep", "diet", "macro counting",
    "keto", "paleo", "vegan", "plant based",
    "intermittent fasting", "fasting", "carnivore diet",
    "supplements", "protein", "pre workout", "vitamins",
    "physical therapy", "injury prevention", "rehab",
    "sports performance", "athletic training", "speed training",
    "flexibility training", "mobility", "foam rolling",
    "meditation", "breathwork", "cold plunge", "sauna",
    "biohacking", "longevity", "anti aging", "optimization",
    "sleep", "sleep optimization", "recovery",
    "mental health", "anxiety", "depression", "stress management",
    "therapy", "counseling", "psychologist",
    "holistic health", "functional medicine", "naturopathy",
    "ayurveda", "traditional chinese medicine", "acupuncture",
    "chiropractic", "osteopath", "physical therapy",
    "womens health", "mens health", "hormone optimization",
    "testosterone", "hormone therapy", "peptides",
    "gut health", "microbiome", "digestive health",
    "skin care", "dermatology", "beauty", "aesthetics",
    "dental", "dentist", "orthodontics",

    // ===== PERSONAL DEVELOPMENT =====
    "personal development", "self improvement", "self help",
    "mindset", "growth mindset", "success mindset",
    "motivation", "discipline", "habits", "atomic habits",
    "productivity", "time management", "deep work", "focus",
    "goal setting", "goal achievement", "vision board",
    "confidence", "self esteem", "self worth",
    "emotional intelligence", "eq", "soft skills",
    "communication skills", "public speaking", "toastmasters",
    "presentation skills", "storytelling", "charisma",
    "leadership", "management", "team building", "team leadership",
    "executive presence", "influence", "persuasion",
    "negotiation skills", "conflict resolution",
    "networking", "professional networking", "business networking",
    "career development", "career change", "career coaching",
    "job search", "resume", "interview skills", "linkedin profile",
    "remote work", "work from home", "digital nomad",
    "work life balance", "time freedom", "financial freedom",
    "morning routine", "evening routine", "daily routine",
    "journaling", "gratitude", "affirmations",
    "reading", "speed reading", "book club", "book summary",
    "memory", "learning", "accelerated learning", "speed learning",
    "brain training", "neuroscience", "neuroplasticity",
    "ikigai", "purpose", "meaning", "fulfillment",
    "stoicism", "philosophy", "wisdom", "ancient wisdom",
    "men", "masculinity", "manhood", "men group",
    "women", "femininity", "women empowerment", "women group",
    "dating", "relationships", "marriage", "couples",
    "dating advice", "dating coach", "attraction",
    "divorce", "co parenting", "blended family",
    "single parent", "parenting", "fatherhood", "motherhood",
    "teen development", "youth", "young adults",

    // ===== SPIRITUALITY & MINDFULNESS =====
    "spirituality", "spiritual growth", "spiritual awakening",
    "meditation", "mindfulness", "zen", "buddhism",
    "manifestation", "law of attraction", "abundance",
    "energy healing", "reiki", "chakra", "crystal healing",
    "astrology", "tarot", "numerology", "psychic",
    "shamanism", "plant medicine", "ayahuasca",
    "consciousness", "enlightenment", "higher self",
    "prayer", "faith", "christian", "bible study",
    "church", "ministry", "pastor", "worship",
    "islam", "quran", "muslim", "jewish",
    "yoga philosophy", "vedanta", "advaita",
    "breath work", "wim hof", "holotropic",
    "sound healing", "sound bath", "singing bowl",
    "sacred geometry", "mysticism", "esoteric",

    // ===== WRITING & PUBLISHING =====
    "writing", "writer", "author", "novelist",
    "fiction writing", "non fiction", "memoir",
    "creative writing", "screenwriting", "scriptwriting",
    "copywriting", "copy", "direct response",
    "technical writing", "business writing", "grant writing",
    "self publishing", "kindle publishing", "amazon kdp",
    "book launch", "book marketing", "bestseller",
    "ghostwriting", "editing", "proofreading",
    "blogging", "blog", "content writing", "article writing",
    "journalism", "investigative journalism", "reporting",
    "poetry", "spoken word", "literary",
    "comic", "graphic novel", "manga",

    // ===== MUSIC & AUDIO =====
    "music", "musician", "music production", "music business",
    "guitar", "piano", "drums", "bass", "violin",
    "singing", "vocal training", "voice", "vocalist",
    "music theory", "songwriting", "composition",
    "music marketing", "music promotion", "spotify",
    "beat making", "hip hop", "rap", "trap",
    "edm", "electronic music", "dj", "djing",
    "ableton", "fl studio", "logic pro", "pro tools",
    "mixing", "mastering", "audio engineering", "recording",
    "podcast production", "audio editing", "voice over",
    "sound design", "foley", "film scoring",
    "music licensing", "sync licensing", "royalty",
    "music teacher", "music lesson", "music school",
    "worship music", "church music", "choir",
    "classical music", "jazz", "blues", "country",
    "rock", "metal", "indie", "alternative",

    // ===== ART & DESIGN =====
    "art", "artist", "fine art", "contemporary art",
    "painting", "drawing", "sketching", "illustration",
    "watercolor", "oil painting", "acrylic painting",
    "digital art", "digital illustration", "digital painting",
    "graphic design", "logo design", "brand design",
    "typography", "lettering", "calligraphy", "hand lettering",
    "animation", "motion graphics", "motion design",
    "3d art", "3d modeling", "blender", "cinema 4d",
    "sculpture", "ceramics", "pottery", "woodworking",
    "jewelry making", "metalwork", "glasswork",
    "printmaking", "screen printing", "linocut",
    "mixed media", "collage", "assemblage",
    "art business", "art marketing", "art gallery",
    "art collecting", "art investment", "art curator",
    "interior design", "home decor", "home staging",
    "architecture", "landscape design", "urban design",
    "fashion design", "textile design", "pattern design",
    "industrial design", "furniture design", "product design",
    "craft", "diy", "maker", "handmade business",
    "sewing", "knitting", "crochet", "quilting",
    "embroidery", "cross stitch", "needlepoint",
    "candle making", "soap making", "bath bomb",
    "floral design", "flower arrangement", "florist",
    "cake decorating", "baking", "pastry",
    "tattoo", "tattoo artist", "body art",

    // ===== EDUCATION & TEACHING =====
    "education", "teaching", "tutoring", "homeschool",
    "online course", "course creation", "course creator",
    "curriculum design", "instructional design", "elearning",
    "coaching certification", "teaching certification",
    "higher education", "college prep", "sat prep", "act prep",
    "grad school", "mba", "phd", "dissertation",
    "language learning", "english", "spanish", "french",
    "german", "mandarin", "japanese", "korean",
    "esl", "tefl", "tesol", "english teacher",
    "math tutoring", "science tutoring", "stem",
    "special education", "dyslexia", "adhd", "autism",
    "montessori", "waldorf", "unschooling",
    "early childhood", "preschool", "elementary",
    "middle school", "high school", "college",
    "study skills", "test prep", "exam prep",
    "professional development", "continuing education",
    "corporate training", "employee training", "onboarding",
    "workshop", "seminar", "masterclass",
    "knowledge business", "info product", "digital product",
    "membership site", "online academy", "learning platform",

    // ===== LAW & LEGAL =====
    "law", "legal", "lawyer", "attorney",
    "law firm", "legal marketing", "legal tech",
    "contract law", "business law", "corporate law",
    "intellectual property", "patent", "trademark", "copyright",
    "real estate law", "family law", "criminal law",
    "immigration law", "employment law", "labor law",
    "tax law", "estate planning", "trust",
    "legal startup", "legaltech", "compliance",
    "mediator", "arbitration", "dispute resolution",
    "paralegal", "legal assistant", "court reporter",

    // ===== HEALTHCARE & MEDICAL =====
    "healthcare", "medical", "doctor", "physician",
    "nurse", "nursing", "nurse practitioner", "rn",
    "medical practice", "private practice", "telehealth",
    "healthcare startup", "health tech", "medtech",
    "pharmacy", "pharmacist", "pharmaceutical",
    "veterinary", "vet", "animal health",
    "dental practice", "dental marketing", "dentist marketing",
    "optometry", "ophthalmology", "eye care",
    "plastic surgery", "cosmetic surgery", "medspa",
    "dermatology", "aesthetics", "botox", "filler",
    "mental health professional", "therapist", "psychologist",
    "counselor", "social worker", "lcsw",
    "occupational therapy", "speech therapy",
    "radiology", "pathology", "anesthesiology",

    // ===== FOOD & BEVERAGE =====
    "cooking", "chef", "culinary", "restaurant",
    "baking", "pastry chef", "cake", "bread",
    "meal prep", "meal planning", "recipe",
    "food blog", "food photography", "food styling",
    "restaurant owner", "restaurant marketing",
    "food truck", "catering", "private chef",
    "bartender", "mixology", "cocktail",
    "wine", "sommelier", "wine tasting",
    "coffee", "barista", "coffee roasting", "latte art",
    "brewery", "craft beer", "home brewing",
    "food science", "food safety", "nutrition science",
    "vegan cooking", "plant based cooking",
    "fermentation", "kombucha", "kimchi", "sourdough",

    // ===== TRAVEL & LIFESTYLE =====
    "travel", "travel blog", "travel photography",
    "travel hacking", "budget travel", "luxury travel",
    "digital nomad", "remote work travel", "van life",
    "backpacking", "solo travel", "adventure travel",
    "travel agent", "travel agency", "travel advisor",
    "expat", "living abroad", "relocation",
    "rv living", "rv travel", "campervan",
    "sailing", "boating", "yacht", "cruise",
    "camping", "glamping", "outdoor adventure",
    "scuba diving", "snorkeling", "freediving",
    "hunting", "fishing", "fly fishing",
    "bird watching", "nature", "conservation",
    "sustainability", "eco friendly", "zero waste",
    "minimalism", "declutter", "simple living",
    "tiny house", "off grid", "homesteading",
    "farm", "farming", "urban farming", "permaculture",
    "gardening", "garden", "landscaping", "lawn care",

    // ===== PETS & ANIMALS =====
    "dog training", "puppy training", "dog behavior",
    "dog breeding", "dog grooming", "dog walking",
    "cat", "cat behavior", "cat breeding",
    "horse", "horseback riding", "equestrian",
    "pet business", "pet sitting", "pet photography",
    "aquarium", "fish keeping", "reptile",
    "bird keeping", "parrot", "exotic pets",
    "animal rescue", "animal shelter", "foster",
    "veterinary business", "vet tech", "animal nutrition",

    // ===== AUTOMOTIVE =====
    "cars", "automotive", "car detailing", "auto repair",
    "car mechanic", "car restoration", "classic cars",
    "car dealership", "car sales", "car flipping",
    "motorcycle", "atv", "off road",
    "electric vehicle", "ev", "tesla",
    "trucking", "truck driver", "cdl",
    "car photography", "automotive marketing",
    "racing", "motorsport", "drag racing", "track day",

    // ===== REAL ESTATE ADJACENT =====
    "home inspector", "home inspection",
    "contractor", "general contractor", "construction",
    "handyman", "home repair", "renovation",
    "plumber", "plumbing", "electrician", "electrical",
    "hvac", "roofing", "painting contractor",
    "pest control", "cleaning business", "maid service",
    "landscaping business", "snow removal", "junk removal",
    "moving company", "storage business",
    "home staging", "home organization",
    "furniture flipping", "thrifting", "reselling",

    // ===== TRADES & SKILLED LABOR =====
    "welding", "machining", "cnc", "fabrication",
    "woodworking", "carpentry", "cabinet making",
    "auto body", "collision repair", "painting",
    "masonry", "concrete", "tile setting",
    "crane operator", "heavy equipment", "excavation",
    "solar installation", "solar energy", "renewable energy",
    "wind energy", "energy efficiency", "green building",
    "locksmith", "glazier", "insulation",

    // ===== KIDS & FAMILY =====
    "parenting", "dad", "mom", "father", "mother",
    "pregnancy", "postpartum", "breastfeeding",
    "baby", "toddler", "preschooler",
    "teen parenting", "teenager", "adolescent",
    "homeschool", "homeschooling", "unschooling",
    "child development", "child psychology",
    "family travel", "family activities", "family fun",
    "kids activities", "kids crafts", "kids education",
    "adoption", "foster care", "foster parent",
    "special needs", "autism parent", "adhd parent",
    "single mom", "single dad", "blended family",
    "marriage", "marriage counseling", "couples therapy",
    "divorce recovery", "co parenting",
    "grandparent", "aging parent", "caregiver",
    "family finance", "teaching kids money",
    "kids sports", "youth sports", "little league",

    // ===== GAMING & ENTERTAINMENT =====
    "gaming", "gamer", "esports", "competitive gaming",
    "game streaming", "twitch streamer", "youtube gaming",
    "game development", "indie game", "game design",
    "board game", "tabletop", "dungeons dragons", "dnd",
    "magic gathering", "card game", "trading card",
    "chess", "poker", "gambling", "sports betting",
    "fantasy sports", "fantasy football", "dfs",
    "entertainment", "comedy", "stand up comedy",
    "improv", "acting", "theater", "film",
    "movie review", "film criticism", "cinema",
    "anime", "manga", "cosplay", "comic con",
    "rpg", "mmorpg", "fps", "battle royale",
    "minecraft", "fortnite", "roblox", "valorant",
    "mobile gaming", "casual gaming", "retro gaming",

    // ===== SCIENCE & RESEARCH =====
    "science", "research", "stem", "physics",
    "chemistry", "biology", "astronomy", "space",
    "ecology", "environmental science", "climate",
    "genetics", "genomics", "bioinformatics",
    "neuroscience", "psychology", "behavioral science",
    "sociology", "anthropology", "political science",
    "economics", "statistics", "mathematics",
    "engineering", "mechanical engineering", "civil engineering",
    "electrical engineering", "chemical engineering",
    "biomedical engineering", "aerospace engineering",
    "robotics", "drone technology", "iot",
    "3d printing", "additive manufacturing",
    "nanotechnology", "quantum computing",

    // ===== NONPROFIT & SOCIAL IMPACT =====
    "nonprofit", "non profit", "ngo", "charity",
    "fundraising", "grant writing", "donor relations",
    "volunteer", "community service", "social impact",
    "social enterprise", "impact investing",
    "diversity", "inclusion", "dei", "equity",
    "environmental", "sustainability", "climate action",
    "human rights", "social justice", "advocacy",
    "philanthropy", "giving", "corporate social responsibility",

    // ===== MISC HIGH-VALUE NICHES =====
    "course creator", "info product", "digital product",
    "community building", "skool", "circle", "mighty networks",
    "membership", "membership site", "subscription",
    "online education", "edtech", "learning management",
    "certification", "accreditation", "continuing education",
    "speaking", "keynote speaker", "motivational speaker",
    "event planning", "conference", "retreat",
    "wedding planning", "wedding business", "wedding vendor",
    "insurance", "life insurance", "health insurance",
    "financial services", "wealth advisor", "cfp",
    "recruiting", "staffing", "talent acquisition",
    "hr", "human resources", "people operations",
    "supply chain", "procurement", "operations",
    "manufacturing", "lean manufacturing", "six sigma",
    "quality management", "iso", "process improvement",
    "import export", "international trade", "customs",
    "franchise", "franchising", "franchise owner",
    "laundromat", "car wash", "atm",
    "dispensary", "cannabis", "hemp", "cbd",
    "beauty salon", "hair salon", "barbershop",
    "nail salon", "esthetician", "lash artist",
    "personal stylist", "fashion", "wardrobe",
    "life insurance agent", "insurance marketing",
    "notary", "virtual notary", "notary business",
    "translation", "interpreter", "localization",
    "sign language", "asl", "deaf community",
    "recovery", "sobriety", "addiction",
    "veteran", "military", "military spouse",
    "faith based", "ministry", "church growth",
    "prepper", "survival", "bushcraft",
    "conspiracy", "true crime", "mystery",
    "paranormal", "ufo", "aliens",
    "biohacking", "quantified self", "wearables",
    "nootropics", "brain supplements", "microdosing",
    "psychedelics", "ketamine therapy", "psilocybin",
    "stem cell", "regenerative medicine",
    "anti aging", "longevity", "lifespan",
    "genetic testing", "23andme", "ancestry",
    "ai coaching", "ai consulting", "ai implementation",  
    "chatbot", "ai chatbot", "conversational ai",
    "voice ai", "text to speech", "speech recognition",
    "computer vision", "autonomous vehicles",
    "space tech", "satellite", "rocket",
    "quantum", "quantum computing", "quantum physics",
    "virtual reality", "vr", "augmented reality", "ar",
    "metaverse", "spatial computing", "apple vision",
    "wearable tech", "smart watch", "fitness tracker",
    "home automation", "smart home", "iot",
    "3d printing business", "cnc business",
    "laser cutting", "engraving", "sublimation",
    "print on demand", "merch", "merchandise",
    "sticker business", "t shirt business", "apparel",
    "packaging design", "label design", "brand packaging",
    "voiceover", "narration", "audiobook",
    "translation services", "copywriting services",
    "bookkeeping services", "tax preparation",
    "property tax appeal", "insurance claim",
    "debt collection", "credit counseling",
    "financial coaching", "money coaching",
    "couples finance", "family budget",
    "estate sale", "auction", "antique",
    "coin collecting", "stamp collecting", "memorabilia",
    "sports card", "pokemon card", "collectible",
    "nft art", "digital collectible", "generative art",
    "web3 community", "dao", "defi protocol",
    "token launch", "ico", "ido", "tokenomics",
    "smart contract audit", "blockchain security",

    // ===== EXPANDED: LONG-TAIL BUSINESS TERMS =====
    "million dollar business", "100k business", "10k month", "first sale",
    "launch strategy", "beta launch", "product launch", "go to market",
    "customer discovery", "user research", "market validation",
    "business automation tools", "systems and processes", "sop",
    "standard operating procedure", "delegation", "hiring",
    "remote team", "offshore team", "team management",
    "employee engagement", "company culture", "workplace",
    "exit strategy", "sell my business", "business broker",
    "licensing", "royalties", "intellectual property",
    "joint venture", "strategic partnership", "collaboration",
    "business credit", "business loan", "sba loan",
    "crowdfunding", "kickstarter", "indiegogo",
    "profit first", "cash flow", "financial management",
    "pricing", "value pricing", "premium pricing",
    "offer creation", "irresistible offer", "value ladder",
    "tripwire", "upsell strategy", "downsell",
    "bundle", "package pricing", "tiered pricing",

    // ===== EXPANDED: SPECIFIC MARKETING METHODS =====
    "retargeting", "remarketing", "lookalike audience",
    "custom audience", "pixel", "facebook pixel", "conversion api",
    "google tag manager", "analytics", "google analytics",
    "a b testing", "split testing", "multivariate testing",
    "heat map", "user behavior", "session recording",
    "chatbot marketing", "messenger marketing", "whatsapp marketing",
    "sms marketing", "text message marketing",
    "native advertising", "sponsored content", "advertorial",
    "programmatic advertising", "display advertising", "banner ads",
    "ott advertising", "connected tv", "podcast advertising",
    "billboard", "out of home", "direct mail",
    "cause marketing", "co branding", "brand collaboration",
    "seasonal marketing", "holiday marketing", "black friday",
    "product seeding", "gifting strategy", "press kit",
    "media pitch", "journalist outreach", "press coverage",
    "podcast guesting", "podcast booking", "podcast tour",
    "summit speaker", "guest expert", "authority building",
    "thought leadership", "industry expert", "keynote",
    "book funnel", "free plus shipping", "challenge funnel",
    "5 day challenge", "boot camp", "workshop funnel",
    "quiz funnel", "assessment funnel", "survey funnel",
    "application funnel", "strategy call", "discovery call",
    "vsl", "video sales letter", "sales page",
    "thank you page", "order bump", "one click upsell",

    // ===== EXPANDED: PLATFORMS & TOOLS =====
    "stan store", "gumroad", "teachable", "thinkific",
    "podia", "patreon", "ko fi", "buy me a coffee",
    "circle community", "discord server", "slack community",
    "telegram group", "facebook group", "linkedin group",
    "school of motion", "skillshare", "udemy", "coursera",
    "canva", "notion", "airtable", "asana", "trello",
    "monday", "clickup", "basecamp", "slack",
    "calendly", "acuity", "booking system",
    "stripe", "paypal", "square", "payment processing",
    "typeform", "tally", "jotform", "google forms",
    "loom", "vidyard", "wistia", "vimeo",
    "later", "buffer", "hootsuite", "sprout social",
    "semrush", "ahrefs", "moz", "surfer seo",
    "jasper ai", "copy ai", "writesonic", "grammarly",
    "descript", "riverside", "squadcast", "zencastr",
    "relume", "framer", "squarespace", "wix",
    "kartra", "samcart", "thrivecart", "paykickstart",
    "leadpages", "unbounce", "instapage", "landing page builder",
    "deadline funnel", "evergreen funnel", "urgency",
    "proof", "social proof", "fomo", "trust badge",
    "hotjar", "crazy egg", "lucky orange",
    "intercom", "drift", "crisp", "live chat",
    "zendesk", "freshdesk", "help scout",
    "mailerlite", "aweber", "constant contact", "drip",
    "lemlist", "instantly", "smartlead", "cold email tool",
    "reply io", "outreach", "sales loft", "apollo",
    "linkedin sales navigator", "linkedin automation",
    "phantombuster", "clay", "clearbit", "zoominfo",

    // ===== EXPANDED: JOB TITLES & ROLES =====
    "ceo", "cfo", "coo", "cto", "cmo",
    "founder", "co founder", "partner",
    "director", "vp", "vice president",
    "manager", "team lead", "supervisor",
    "analyst", "strategist", "coordinator",
    "specialist", "expert", "advisor",
    "associate", "assistant", "intern",
    "account executive", "account manager",
    "customer success manager", "project manager",
    "product owner", "scrum master", "developer",
    "engineer", "architect", "designer",
    "content manager", "brand manager", "growth lead",
    "demand gen", "demand generation", "growth hacker",
    "full stack marketer", "t shaped marketer",
    "fractional cmo", "fractional cfo", "fractional cto",
    "interim", "advisor board", "board member",

    // ===== EXPANDED: METHODOLOGIES & FRAMEWORKS =====
    "okr", "kpi", "north star metric", "balanced scorecard",
    "lean canvas", "business model canvas", "value proposition canvas",
    "jobs to be done", "jtbd", "design thinking",
    "design sprint", "sprint", "mvp testing",
    "customer journey", "buyer persona", "ideal customer profile",
    "icp", "tam sam som", "product market fit",
    "pirate metrics", "aarrr", "growth loops",
    "flywheel", "compound growth", "network effect",
    "blue ocean strategy", "red ocean", "moat",
    "competitive advantage", "unfair advantage", "first mover",
    "second mover", "fast follower", "category design",
    "positioning", "messaging", "value proposition",
    "unique selling proposition", "usp", "differentiation",
    "pricing strategy", "freemium", "free trial",
    "product led growth", "plg", "bottom up",
    "enterprise selling", "land and expand",
    "customer lifetime value", "clv", "ltv",
    "cost per acquisition", "cpa", "cac",
    "return on ad spend", "roas", "roi",
    "attribution", "multi touch attribution",
    "marketing mix", "4ps", "7ps",

    // ===== EXPANDED: INDUSTRY VERTICALS =====
    "saas marketing", "b2b marketing", "b2c marketing",
    "healthcare marketing", "medical marketing",
    "legal marketing", "law firm marketing",
    "financial marketing", "fintech", "wealthtech",
    "proptech", "real estate tech", "construction tech",
    "edtech", "hrtech", "martech",
    "adtech", "regtech", "insurtech",
    "foodtech", "agtech", "cleantech",
    "biotech", "medtech", "healthtech",
    "logistics tech", "supply chain tech",
    "automotive tech", "mobility", "micromobility",
    "govtech", "civic tech", "public sector",
    "defense", "military tech", "aerospace",
    "energy tech", "oil gas", "mining",
    "fashion tech", "retail tech", "commerce",
    "sports tech", "entertainment tech", "mediatech",
    "music tech", "creative tech", "design tech",

    // ===== EXPANDED: INCOME & MONETIZATION =====
    "make money online", "earn money", "income stream",
    "passive income ideas", "semi passive income",
    "royalty income", "licensing income",
    "rental income ideas", "cash flow investing",
    "dividend income", "covered calls", "option income",
    "freelance income", "consulting income",
    "coaching income", "course income", "info product income",
    "affiliate income", "commission income",
    "sponsorship income", "brand deal income",
    "adsense", "ad revenue", "monetization",
    "membership income", "community income",
    "saas revenue", "software revenue",
    "ecommerce revenue", "product revenue",
    "service business", "productized service",
    "done for you", "done with you", "diy",
    "retainer model", "project based", "hourly billing",
    "value based pricing", "outcome based pricing",
    "performance based", "commission based",
    "equity compensation", "profit sharing",
    "revenue share", "joint venture income",

    // ===== EXPANDED: DEMOGRAPHIC SPECIFIC =====
    "women entrepreneur", "female founder", "mom entrepreneur",
    "mompreneur", "work from home mom", "stay at home mom",
    "dadpreneur", "father entrepreneur",
    "teen entrepreneur", "student entrepreneur", "college entrepreneur",
    "young professional", "millennial", "gen z",
    "baby boomer", "retiree", "second career",
    "immigrant entrepreneur", "minority business",
    "black owned business", "hispanic business", "asian business",
    "lgbtq business", "disabled entrepreneur",
    "military veteran business", "spouse business",
    "senior fitness", "over 40 fitness", "over 50",
    "teen fitness", "youth fitness", "kids fitness",
    "prenatal fitness", "postnatal fitness",
    "couples fitness", "family fitness",

    // ===== EXPANDED: SPECIFIC SKILLS & SERVICES =====
    "logo design service", "web design service",
    "branding service", "naming", "company naming",
    "brand photography", "headshot", "professional photo",
    "virtual event", "hybrid event", "in person event",
    "corporate event", "team retreat", "off site",
    "trade show", "expo", "convention",
    "booth design", "exhibition", "showcase",
    "press conference", "product unveil", "launch event",
    "gala", "fundraiser event", "benefit",
    "award show", "ceremony", "recognition",
    "hackathon", "pitch competition", "demo day",
    "accelerator", "incubator", "startup program",
    "coworking", "shared office", "hot desk",
    "virtual office", "registered agent",
    "business incorporation", "llc", "s corp", "c corp",
    "dba", "ein", "business registration",
    "trademark registration", "patent filing",
    "nda", "operating agreement", "shareholders agreement",
    "term sheet", "cap table", "vesting",
    "convertible note", "safe note", "priced round",

    // ===== EXPANDED: NICHE HOBBIES & INTERESTS =====
    "lego", "model building", "rc car", "rc airplane",
    "drone racing", "fpv racing", "sim racing",
    "flight simulator", "train simulator",
    "aquascaping", "terrarium", "vivarium",
    "bonsai", "orchid", "succulent", "houseplant",
    "bird watching", "bird photography", "wildlife tracking",
    "stargazing", "telescope", "astrophotography",
    "metal detecting", "treasure hunting", "geocaching",
    "lock picking", "escape room", "puzzle",
    "magic tricks", "card magic", "mentalism",
    "juggling", "circus", "acrobatics",
    "ballroom dance", "salsa", "bachata", "swing dance",
    "hip hop dance", "contemporary dance", "ballet",
    "pole dancing", "pole fitness", "aerial silks",
    "figure skating", "ice hockey", "curling",
    "archery", "fencing", "shooting sports",
    "paintball", "airsoft", "nerf",
    "disc golf", "ultimate frisbee", "cornhole",
    "bowling", "darts", "billiards", "pool",
    "table tennis", "badminton", "squash", "racquetball",
    "water polo", "rowing", "kayaking", "canoeing",
    "paddle boarding", "wake boarding", "water skiing",
    "kite surfing", "wind surfing", "jet skiing",
    "paragliding", "hang gliding", "skydiving",
    "base jumping", "bungee jumping", "zip lining",
    "trail running", "ultra marathon", "obstacle course",
    "spartan race", "tough mudder", "iron man",
    "cross country", "track and field", "decathlon",
    "wrestling", "judo", "krav maga", "wing chun",
    "tai chi", "qigong", "kung fu",

    // ===== EXPANDED: SPECIFIC HEALTH CONDITIONS =====
    "pcos", "endometriosis", "fertility",
    "ivf", "pregnancy loss", "miscarriage",
    "menopause", "perimenopause", "hot flashes",
    "thyroid", "hashimoto", "hypothyroid",
    "diabetes", "type 2 diabetes", "insulin resistance",
    "autoimmune", "lupus", "fibromyalgia",
    "chronic fatigue", "chronic pain", "pain management",
    "migraine", "headache", "tension",
    "back pain", "sciatica", "herniated disc",
    "knee pain", "shoulder pain", "hip pain",
    "plantar fasciitis", "tendonitis", "carpal tunnel",
    "heart disease", "cardiovascular", "blood pressure",
    "cholesterol", "stroke prevention", "heart health",
    "cancer", "cancer survivor", "oncology",
    "alzheimer", "dementia", "brain health",
    "parkinson", "multiple sclerosis", "als",
    "epilepsy", "seizure", "neurology",
    "eating disorder", "anorexia", "bulimia",
    "binge eating", "food addiction", "emotional eating",
    "ocd", "ptsd", "trauma", "trauma healing",
    "grief", "loss", "bereavement",
    "anger management", "impulse control",
    "social anxiety", "panic attack", "phobia",
    "insomnia", "narcolepsy", "sleep apnea",
    "tinnitus", "hearing loss", "deaf",
    "vision loss", "blindness", "low vision",
    "chronic illness", "invisible illness", "disability",
    "wheelchair", "prosthetics", "adaptive",
    "scoliosis", "posture", "ergonomics",
    "tmj", "jaw pain", "dental anxiety",

    // ===== EXPANDED: CREATIVE ECONOMY =====
    "nft creator", "digital art marketplace", "opensea",
    "foundation", "superrare", "rarible",
    "art drops", "limited edition", "art prints",
    "print shop", "art store", "online gallery",
    "commission art", "portrait commission", "pet portrait",
    "caricature", "cartoon", "character design",
    "concept art", "game art", "pixel art",
    "voxel art", "low poly", "isometric",
    "procreate", "ipad art", "apple pencil",
    "wacom", "drawing tablet", "digital canvas",
    "art therapy", "art journal", "creative journaling",
    "vision boarding", "mood board", "aesthetic",
    "color theory", "color palette", "design principles",
    "gestalt", "composition rules", "golden ratio",
    "branding kit", "brand board", "style guide",
    "social media templates", "canva templates",
    "instagram templates", "pinterest templates",
    "wedding invitation", "stationery", "greeting card",
    "planner design", "printable", "digital download",
    "digital planner", "goodnotes", "notability",
    "ebook design", "book cover", "magazine layout",
    "infographic", "data visualization", "chart design",
    "icon design", "emoji design", "sticker design",
    "pattern design", "wallpaper design", "textile print",
    "surface design", "fabric design", "fashion illustration",

    // ===== EXPANDED: WEALTH & LUXURY =====
    "wealth building", "wealth creation", "millionaire",
    "billionaire", "ultra high net worth", "family office",
    "private banking", "asset management", "portfolio",
    "tax free", "offshore", "asset protection",
    "trust fund", "generational wealth", "inheritance",
    "luxury lifestyle", "luxury travel", "first class",
    "private jet", "yacht charter", "luxury car",
    "watch collecting", "rolex", "luxury watch",
    "wine investing", "art investing", "collectible investing",
    "luxury real estate", "mansion", "penthouse",
    "country club", "golf club", "members club",

    // ===== EXPANDED: EMERGING TRENDS 2024-2025 =====
    "ai agent building", "autonomous ai", "ai assistant",
    "rag", "retrieval augmented generation", "vector database",
    "fine tuning", "model training", "llm",
    "large language model", "open source ai", "llama",
    "mistral", "anthropic", "perplexity",
    "ai search", "ai seo", "ai content",
    "ai video generation", "sora", "kling",
    "ai image generation", "flux", "ideogram",
    "ai voice", "elevenlabs", "play ht",
    "ai music generation", "suno", "udio",
    "ai coding", "cursor", "copilot", "codeium",
    "ai productivity", "ai workflow automation",
    "ai sales assistant", "ai customer service",
    "ai marketing", "ai analytics", "predictive ai",
    "creator tools", "creator studio", "creator fund",
    "tiktok creator fund", "youtube partner",
    "shorts fund", "reels bonus", "creator marketplace",
    "ugc agency", "ugc portfolio", "ugc pricing",
    "faceless brand", "faceless business", "automation business",
    "cash cow youtube", "youtube automation business",
    "clip channel", "compilation channel", "reaction channel",
    "newsletter business", "paid newsletter", "premium content",
    "community business", "paid community", "premium community",
    "cohort based course", "live course", "group program",
    "challenge launch", "webinar launch", "evergreen launch",
    "low ticket offer", "mid ticket", "high ticket offer",
    "ascension model", "value ladder business",
    "white label saas", "reseller", "saas reseller",
    "api business", "developer tools", "dev tools",
    "chrome extension", "browser extension", "plugin",
    "wordpress plugin", "shopify app", "shopify theme",
    "template business", "notion template", "canva template",
    "figma template", "webflow template", "framer template",
    "ai wrapper", "gpt wrapper", "ai tool builder",
    "micro startup", "weekend project", "build in public",
    "indie maker", "solo developer", "one person business",
    "calm company", "lifestyle business", "bootstrapped saas",
    "revenue first", "ramen profitable", "default alive",

    // ===== FINAL EXPANSION: 300+ ADDITIONAL SEARCHES =====
    "accountability partner", "body language", "cold shower",
    "dopamine detox", "ego death", "flow state",
    "gratitude practice", "high performance", "inner child",
    "journal prompts", "kundalini", "manifestation journal",
    "nervous system regulation", "overcome fear", "peak performance",
    "quantum leap", "radical acceptance", "shadow work",
    "third eye", "unconscious mind", "vibrational frequency",
    "wealth consciousness", "yin yoga",
    "aura reading", "birth chart", "cosmic energy",
    "divine feminine", "divine masculine", "empath",
    "human design", "gene keys", "akashic records",
    "past lives", "soul purpose", "twin flame",
    "angel numbers", "oracle cards", "spirit guide",
    "cacao ceremony", "ecstatic dance", "kirtan",
    "holistic nutrition", "intuitive eating", "food freedom",
    "body positivity", "self love", "inner peace",
    "emotional healing", "somatic experiencing", "emdr",
    "cognitive behavioral therapy", "cbt", "dbt",
    "attachment theory", "codependency", "boundaries",
    "people pleasing", "assertiveness", "vulnerability",
    "authentic self", "imposter syndrome", "perfectionism",
    "burnout", "burnout recovery", "stress relief",
    "cortisol", "adrenal fatigue", "hpa axis",
    "circadian rhythm", "blue light", "screen time",
    "forest bathing", "grounding", "earthing",
    "oil pulling", "dry brushing", "gua sha",
    "face yoga", "facial exercise", "mewing",
    "tongue tie", "sleep training baby", "gentle parenting",
    "conscious parenting", "respectful parenting", "positive discipline",
    "farm to table", "organic food", "clean eating",
    "whole food", "raw food", "juice cleanse",
    "detox", "liver cleanse", "parasite cleanse",
    "collagen", "bone broth", "electrolytes",
    "creatine", "ashwagandha", "lion mane",
    "turkey tail", "reishi", "cordyceps",
    "functional mushroom", "adaptogens", "herbal medicine",
    "essential oils", "aromatherapy", "herbalism",
    "homeopathy", "bach flower", "flower essence",
    "reflexology", "craniosacral", "myofascial release",
    "trigger point", "deep tissue massage", "sports massage",
    "lymphatic drainage", "cupping therapy", "dry needling",
    "pelvic floor", "diastasis recti", "prolapse",
    "strength for runners", "strength for swimmers",
    "strength for cyclists", "strength for golfers",
    "strength for tennis", "strength for basketball",
    "home gym", "garage gym", "gym equipment",
    "resistance bands", "kettlebell", "dumbbells",
    "barbell", "pull up bar", "squat rack",
    "treadmill", "rowing machine", "spin bike",
    "peloton", "mirror gym", "tonal",
    "apple fitness", "fitbit", "garmin",
    "whoop", "oura ring", "continuous glucose monitor",
    "zone 2 training", "heart rate training", "vo2 max",
    "lactate threshold", "periodization", "progressive overload",
    "reverse dieting", "metabolism", "basal metabolic rate",
    "tdee", "calorie deficit", "calorie surplus",
    "lean bulk", "clean bulk", "body recomposition",
    "contest prep", "bodybuilding competition", "physique",
    "bikini competition", "figure competition", "classic physique",
    "strongman", "highland games", "arm wrestling",
    "grip strength", "forearm training", "neck training",
    "neck training football", "concussion prevention",
    "return to sport", "acl recovery", "rotator cuff",
    "senior exercise", "chair exercise", "balance training",
    "fall prevention", "bone density", "osteoporosis",
    "arthritis", "joint health", "glucosamine",
    "collagen peptides", "hyaluronic acid", "msm",
    "turmeric", "curcumin", "omega 3",
    "fish oil", "vitamin d", "magnesium",
    "zinc", "b12", "iron deficiency",
    "hormone panel", "bloodwork", "lab results",
    "dna test", "epigenetics", "telomere",
    "stem cell therapy", "prp", "platelet rich plasma",
    "peptide therapy", "bpc 157", "tb 500",
    "nad", "iv therapy", "ozone therapy",
    "hyperbaric oxygen", "red light therapy", "infrared",
    "emf protection", "air purifier", "water filter",
    "reverse osmosis", "spring water", "hydrogen water",
    "structured water", "alkaline water",
    "elimination diet", "fodmap", "leaky gut",
    "sibo", "candida", "food sensitivity",
    "allergy testing", "histamine intolerance",
    "celiac", "gluten free", "dairy free",
    "sugar free", "low carb", "high protein",
    "meal delivery", "hello fresh", "factor",
    "soylent", "huel", "meal replacement",
    "protein shake", "smoothie bowl", "acai bowl",
    "kombucha brewing", "water kefir", "jun tea",
    "probiotic", "prebiotic", "postbiotic",
    "functional food", "superfood", "spirulina",
    "chlorella", "moringa", "maca",
    "cacao", "matcha", "yerba mate",
    "nootropic stack", "modafinil", "alpha gpc",
    "l theanine", "caffeine", "focus supplement",
    "cognitive enhancement", "memory supplement",
    "sports nutrition", "endurance nutrition", "race nutrition",
    "hydration", "electrolyte drink", "salt tabs",
    "carb loading", "bonking", "glycogen",
    "marathon training plan", "5k training", "10k training",
    "half marathon", "couch to 5k", "running form",
    "minimalist running", "barefoot running", "trail shoes",
    "hiking gear", "camping gear", "backpacking gear",
    "ultralight", "thru hiking", "appalachian trail",
    "pacific crest trail", "camino de santiago",
    "overlanding", "4x4", "jeep wrangler",
    "truck camper", "roof top tent", "car camping",
    "fire making", "wilderness survival", "first aid",
    "wilderness first responder", "sar", "search and rescue",
    "ham radio", "amateur radio", "emergency communication",
    "solar panel", "battery bank", "portable power",
    "generator", "inverter", "off grid solar",
    "rainwater harvesting", "well water", "septic system",
    "composting toilet", "grey water", "earth building",
    "cob house", "straw bale", "rammed earth",
    "shipping container home", "a frame", "cabin",
    "log cabin", "tree house", "dome home",
    "yurt", "geodesic dome", "earthship"
];

/**
 * Generiše niz startUrl-ova za Skool Discovery pretragu.
 */
export function generateStartUrls() {
    const urls = [
        'https://www.skool.com/discovery', // Glavni feed
    ];
    
    for (const keyword of NICHE_KEYWORDS) {
        const encoded = encodeURIComponent(keyword).replace(/%20/g, '+');
        urls.push(`https://www.skool.com/discovery?q=${encoded}`);
    }
    
    return urls;
}

export { NICHE_KEYWORDS };
