/**
 * NICHE KEYWORD DATABASE — Community & Lifestyle Focused
 * Real topics people build communities around.
 * Platforms and software tools are intentionally excluded.
 */

const NICHE_KEYWORDS = [

    // ===== HEALTH & FITNESS =====
    "fitness", "gym", "workout", "exercise", "weight loss",
    "fat loss", "body transformation", "muscle building", "bodybuilding",
    "strength training", "powerlifting", "weightlifting", "olympic lifting",
    "crossfit", "hiit", "cardio", "calisthenics", "bodyweight training",
    "home workout", "yoga", "pilates", "barre", "stretching", "flexibility",
    "mobility", "foam rolling", "recovery", "injury prevention", "rehab",
    "running", "marathon", "half marathon", "5k", "10k", "couch to 5k",
    "trail running", "ultra marathon", "spartan race", "tough mudder",
    "cycling", "triathlon", "swimming", "rowing", "kayaking", "hiking",
    "rock climbing", "bouldering", "surfing", "snowboarding", "skiing",
    "golf", "tennis", "pickleball", "basketball", "soccer", "volleyball",
    "boxing", "mma", "muay thai", "bjj", "jiu jitsu", "wrestling",
    "martial arts", "self defense", "kickboxing", "karate", "judo",
    "personal trainer", "fitness coach", "online coaching",
    "fitness business", "gym owner", "fitness marketing",
    "sports performance", "athletic training", "speed training",
    "nutrition", "meal prep", "diet", "macro counting",
    "keto", "paleo", "vegan", "plant based", "carnivore diet",
    "intermittent fasting", "supplements", "protein",
    "biohacking", "longevity", "anti aging", "sleep optimization",
    "cold plunge", "sauna", "breathwork",
    "womens fitness", "mens fitness", "senior fitness", "over 40 fitness",
    "prenatal fitness", "postnatal fitness", "kids fitness", "youth sports",
    "bodybuilding competition", "physique", "bikini competition",
    "home gym", "garage gym", "kettlebell", "resistance bands",

    // ===== MENTAL HEALTH & WELLBEING =====
    "mental health", "anxiety", "depression", "stress management",
    "therapy", "counseling", "mindset", "mindfulness", "meditation",
    "breathwork", "journaling", "gratitude", "affirmations",
    "burnout recovery", "trauma healing", "grief", "emotional healing",
    "shadow work", "inner child", "self love", "self esteem", "confidence",
    "boundaries", "codependency", "people pleasing", "perfectionism",
    "imposter syndrome", "overthinking", "anger management",
    "social anxiety", "panic attacks", "ocd", "ptsd",
    "productivity", "focus", "deep work", "time management",
    "morning routine", "daily habits", "atomic habits",
    "stoicism", "philosophy", "wisdom",

    // ===== NUTRITION & HEALTH =====
    "gut health", "microbiome", "digestive health", "inflammation",
    "skin care", "holistic health", "functional medicine", "naturopathy",
    "ayurveda", "traditional chinese medicine", "acupuncture",
    "hormone health", "hormone optimization", "testosterone",
    "womens health", "pcos", "endometriosis", "fertility", "menopause",
    "thyroid", "diabetes", "autoimmune", "chronic fatigue", "chronic pain",
    "cancer survivor", "heart health", "blood pressure",
    "clean eating", "whole food", "organic food", "food freedom",
    "intuitive eating", "body positivity",
    "essential oils", "herbalism", "homeopathy",
    "red light therapy", "infrared sauna",
    "collagen", "bone broth", "adaptogens", "nootropics",

    // ===== PERSONAL DEVELOPMENT =====
    "personal development", "self improvement", "self help",
    "growth mindset", "success mindset", "motivation", "discipline",
    "productivity", "goal setting", "vision board", "leadership",
    "communication skills", "public speaking", "charisma", "influence",
    "emotional intelligence", "networking", "professional networking",
    "career development", "career change", "remote work", "digital nomad",
    "work life balance", "time freedom", "financial freedom",
    "reading", "book club", "speed reading", "learning",
    "memory training", "accelerated learning",
    "purpose", "fulfillment", "meaning", "ikigai",
    "men community", "masculinity", "manhood", "mens group",
    "women empowerment", "women community", "female leaders",
    "dating", "relationships", "marriage", "couples",
    "dating coach", "attraction", "divorce recovery", "co parenting",
    "parenting", "fatherhood", "motherhood", "conscious parenting",
    "single mom", "single dad", "blended family",
    "teen development", "youth empowerment",

    // ===== SPIRITUALITY =====
    "spirituality", "spiritual growth", "spiritual awakening",
    "manifestation", "law of attraction", "abundance mindset",
    "energy healing", "reiki", "chakra", "crystal healing",
    "astrology", "tarot", "numerology", "human design",
    "shamanism", "plant medicine", "consciousness",
    "prayer", "faith", "christian community", "bible study",
    "church community", "ministry", "worship",
    "yoga philosophy", "meditation teacher",
    "sound healing", "sound bath", "breathwork",

    // ===== BUSINESS & ENTREPRENEURSHIP =====
    "business", "entrepreneurship", "startup", "small business",
    "online business", "business coaching", "business growth",
    "solopreneur", "side hustle", "passive income",
    "women in business", "young entrepreneur", "serial entrepreneur",
    "business mastermind", "accountability group", "ceo group",
    "business scaling", "business systems", "delegation",
    "franchise", "local business", "home business",
    "business exit", "sell my business",
    "make money online", "income streams",
    "high ticket", "high ticket sales", "high ticket coaching",

    // ===== MARKETING & SALES =====
    "marketing", "digital marketing", "content marketing", "email marketing",
    "social media marketing", "influencer marketing", "affiliate marketing",
    "copywriting", "sales", "sales coaching", "cold outreach",
    "lead generation", "personal brand", "brand building",
    "facebook ads", "instagram ads", "tiktok ads", "google ads",
    "seo", "organic traffic", "content strategy",
    "agency", "smma", "social media agency", "marketing agency",

    // ===== CONTENT CREATION =====
    "content creator", "youtube", "youtuber", "youtube growth",
    "tiktok creator", "tiktok growth", "instagram growth",
    "podcasting", "podcast growth", "newsletter", "blogging",
    "video editing", "video production", "thumbnail design",
    "live streaming", "faceless youtube", "youtube automation",
    "short form content", "reels", "ugc creator",
    "influencer", "brand deals", "sponsorship",
    "community building", "audience building",

    // ===== COACHING =====
    "coaching", "life coaching", "executive coaching",
    "health coaching", "wellness coaching", "nutrition coaching",
    "fitness coaching", "mindset coaching", "relationship coaching",
    "career coaching", "group coaching", "coaching program",
    "coaching business", "coaching certification",
    "transformational coaching", "nlp",

    // ===== REAL ESTATE =====
    "real estate", "real estate investing", "rental property",
    "house flipping", "wholesale real estate", "multifamily investing",
    "airbnb", "short term rental", "real estate agent",
    "property management", "commercial real estate",
    "land investing", "storage units", "laundromat",

    // ===== FINANCE & INVESTING =====
    "financial freedom", "personal finance", "financial literacy",
    "investing", "stock market", "options trading", "swing trading",
    "day trading", "forex trading", "crypto", "bitcoin",
    "index funds", "dividend investing", "retirement planning",
    "tax strategy", "budgeting", "debt free", "wealth building",
    "generational wealth", "financial coaching",
    "trading", "trading psychology", "technical analysis",
    "price action", "prop firm", "funded trader",

    // ===== CREATIVE ARTS =====
    "photography", "photographer", "portrait photography",
    "wedding photography", "landscape photography",
    "food photography", "travel photography",
    "drone photography", "film photography",
    "videography", "wedding videography", "documentary",
    "graphic design", "logo design", "brand design",
    "illustration", "digital art", "painting", "watercolor",
    "drawing", "sketching", "animation", "motion graphics",
    "3d modeling", "blender art", "sculpture", "ceramics", "pottery",
    "jewelry making", "woodworking", "carpentry",
    "sewing", "knitting", "crochet", "embroidery", "quilting",
    "candle making", "soap making", "floral design",
    "calligraphy", "hand lettering", "tattoo artist",
    "interior design", "home decor", "home staging",

    // ===== MUSIC =====
    "music", "musician", "music production", "songwriting",
    "guitar", "piano", "drums", "singing", "vocal training",
    "beat making", "hip hop producer", "dj", "djing",
    "music business", "music marketing", "spotify growth",
    "ableton", "fl studio", "logic pro",
    "mixing", "mastering", "audio engineering",
    "music teacher", "music lessons",
    "jazz", "blues", "country", "classical music",

    // ===== WRITING & PUBLISHING =====
    "writing", "author", "fiction writing", "novel writing",
    "self publishing", "kindle publishing", "book launch",
    "copywriting", "ghostwriting", "content writing",
    "screenwriting", "poetry", "creative writing",
    "blogging", "journalism",

    // ===== TRAVEL & LIFESTYLE =====
    "travel", "travel hacking", "budget travel", "luxury travel",
    "digital nomad", "van life", "rv living", "backpacking",
    "solo travel", "adventure travel", "expat", "living abroad",
    "sailing", "boating", "camping", "glamping",
    "scuba diving", "freediving", "surfing",
    "hunting", "fishing", "fly fishing",
    "sustainability", "zero waste", "minimalism",
    "tiny house", "off grid", "homesteading", "permaculture",
    "gardening", "urban farming", "beekeeping",

    // ===== FOOD & BEVERAGE =====
    "cooking", "chef", "culinary", "baking", "bread making",
    "pastry", "cake decorating", "meal prep", "recipe",
    "food blog", "restaurant owner", "food truck", "catering",
    "wine", "sommelier", "coffee", "barista", "craft beer", "home brewing",
    "fermentation", "kombucha", "sourdough",
    "vegan cooking", "plant based cooking",

    // ===== PETS & ANIMALS =====
    "dog training", "puppy training", "dog behavior",
    "dog grooming", "pet business", "pet photography",
    "horse", "horseback riding", "equestrian",
    "animal rescue", "pet sitting",

    // ===== KIDS & FAMILY =====
    "homeschool", "homeschooling", "child development",
    "family travel", "kids activities", "special needs parenting",
    "autism parent", "adhd parent", "pregnancy", "postpartum", "breastfeeding",
    "fertility", "adoption", "foster parent",

    // ===== GAMING & HOBBIES =====
    "gaming", "esports", "game streaming", "twitch streamer",
    "chess", "poker", "board game", "tabletop rpg", "dungeons dragons",
    "magic gathering", "sports cards", "trading cards",
    "stand up comedy", "acting", "improv theater",
    "dance", "salsa", "ballroom dance", "hip hop dance", "ballet",
    "yoga teacher", "pilates instructor",
    "lego", "model building", "rc cars", "drone racing",
    "aquascaping", "bonsai", "orchid growing", "houseplants",
    "stargazing", "astrophotography", "bird watching",
    "archery", "shooting sports", "disc golf",
    "bowling", "billiards",
    "crossfit community", "spartan community",

    // ===== PROFESSIONAL & CAREER =====
    "consulting", "freelancing", "virtual assistant",
    "ecommerce", "dropshipping", "amazon fba", "etsy seller",
    "print on demand",
    "real estate agent", "mortgage broker",
    "lawyer", "attorney", "legal", "law firm",
    "doctor", "nurse", "therapist", "dentist",
    "teacher", "tutor", "homeschool teacher",
    "nonprofit", "charity", "social impact", "volunteer",
    "veteran", "military", "military spouse",
    "faith based", "church growth", "ministry",

    // ===== SPECIFIC COMMUNITIES =====
    "mastermind", "accountability", "peer group", "mens group", "womens group",
    "paid community", "membership community",
    "wealth", "millionaire mindset",
    "recovery", "sobriety", "addiction recovery",
    "cancer community", "chronic illness", "invisible illness",
    "lgbtq community", "minority entrepreneur",
    "black entrepreneur", "latina entrepreneur",
    "over 50", "retiree", "second career",
    "college student", "young professional", "millennial",

    // ===== FITNESS DEEP EXPANSION =====
    "abs training", "core strength", "six pack", "back pain exercise",
    "posture correction", "neck pain", "shoulder mobility", "hip mobility",
    "glute training", "leg day", "arm training", "chest workout",
    "pull day", "push day", "legs day", "ppl program",
    "5x5", "starting strength", "stronglifts", "nsuns", "wendler 531",
    "juggernaut training", "conjugate method", "westside barbell",
    "powerlifting meet", "bench press", "squat technique", "deadlift",
    "sumo deadlift", "romanian deadlift", "overhead press",
    "barbell row", "pull up", "chin up", "muscle up",
    "planche", "front lever", "human flag", "handstand",
    "handstand push up", "ring dips", "ring muscle up",
    "jump rope", "agility training", "ladder drills",
    "plyometrics", "box jumps", "vertical jump",
    "wrestling training", "grappling", "submission wrestling",
    "no gi bjj", "gi bjj", "white belt", "blue belt", "purple belt",
    "weight class", "cutting weight", "water cut",
    "marathon pace", "race training", "running club", "run streak",
    "5k pr", "half marathon training", "ultralight hiking",
    "mountain biking", "road cycling", "gravel cycling", "zwift",
    "triathlon training", "ironman training", "olympic triathlon",
    "open water swimming", "masters swimming", "swim technique",
    "water polo training", "polo", "equestrian jumping",
    "show jumping", "dressage", "barrel racing",
    "rodeo", "bull riding", "team roping",
    "motocross", "supercross", "enduro", "adventure motorcycle",
    "bmx", "bmx racing", "bmx tricks", "mountain bike trail",
    "skateboard tricks", "longboard", "inline skating",
    "ice skating", "figure skating", "speed skating",
    "nordic skiing", "cross country skiing", "ski touring",
    "backcountry skiing", "avalanche training",
    "kiteboarding", "kite surfing", "windsurfing",
    "white water kayaking", "rafting", "stand up paddle",
    "outrigger canoe", "dragon boat", "crew rowing",
    "weightlifting team", "powerlifting federation",
    "natural bodybuilding", "tested bodybuilding",
    "masters bodybuilding", "physique competitor",
    "wellness competition", "figure athlete",

    // ===== YOGA & MOVEMENT DEEP EXPANSION =====
    "hatha yoga", "vinyasa yoga", "ashtanga yoga", "iyengar yoga",
    "yin yoga", "restorative yoga", "hot yoga", "bikram yoga",
    "aerial yoga", "acro yoga", "goat yoga", "laughter yoga",
    "yoga for athletes", "yoga for runners", "yoga for cyclists",
    "yoga for back pain", "yoga for beginners", "advanced yoga",
    "yoga teacher training", "300 hour yoga", "200 hour yoga",
    "prenatal yoga", "postnatal yoga", "kids yoga", "seniors yoga",
    "yoga retreat", "yoga challenge", "30 day yoga",
    "pilates reform", "reformer pilates", "mat pilates",
    "clinical pilates", "pilates for back", "pilates instructor",
    "barre fitness", "barre instructor", "ballet barre",
    "tai chi class", "qigong practice", "chi kung",
    "somatics", "feldenkrais", "alexander technique",
    "movement coach", "movement practice", "embodiment",
    "dance fitness", "zumba", "jazzercise", "step aerobics",
    "pole fitness", "pole dancing beginner", "pole tricks",
    "aerial silks", "aerial hoop", "lyra", "aerial fitness",
    "contortion", "flexibility training adult",

    // ===== OUTDOOR & ADVENTURE DEEP =====
    "backpacking trips", "thru hiking", "long distance hiking",
    "day hiking", "hiking club", "trail maintenance",
    "camping meals", "camp cooking", "cast iron cooking",
    "wilderness cooking", "dutch oven", "camp coffee",
    "canoe camping", "kayak camping", "packrafting",
    "bikepacking", "cycle touring", "gravel adventure",
    "climbing gym", "bouldering gym", "lead climbing",
    "trad climbing", "sport climbing", "alpine climbing",
    "mountaineering", "high altitude", "summit climbing",
    "climbing gear", "harness", "climbing shoes", "crash pad",
    "deep water soloing", "via ferrata",
    "caving", "spelunking", "cave diving",
    "paragliding lessons", "paragliding XC",
    "hang gliding training", "powered paraglider",
    "skydiving beginner", "aff training", "wingsuit",
    "base jumping", "speed flying", "slacklining", "highlining",
    "orienteering", "navigation", "map reading",
    "bushcraft skills", "wilderness survival", "wild edibles",
    "foraging", "mushroom foraging", "plant identification",
    "bow hunting", "rifle hunting", "turkey hunting",
    "deer hunting", "waterfowl hunting", "big game hunting",
    "fishing guide", "bass fishing", "trout fishing",
    "saltwater fishing", "ice fishing", "carp fishing",
    "fly tying", "fly fishing guide", "spearfishing",
    "free diving", "spear fishing, lobster diving",
    "scuba certification", "open water diver", "dive master",
    "underwater photography", "cave diving",
    "freedive training", "apnea training",
    "sailing lessons", "bluewater sailing", "ocean crossing",
    "liveaboard sailing", "coastal navigation", "passage making",
    "boat restoration", "wooden boat", "sailing community",
    "powerboat", "offshore racing", "racing yacht",
    "kiteboarding lessons", "kiteboarding community",

    // ===== NUTRITION & DIET DEEP =====
    "carnivore diet", "lion diet", "zero carb", "animal based",
    "organ meats", "nose to tail", "grass fed beef",
    "raw milk", "raw food diet", "living foods",
    "water fasting", "extended fasting", "autophagy",
    "dry fasting", "juice fasting", "master cleanse",
    "gut healing", "leaky gut protocol", "sibo diet",
    "fodmap diet", "low fodmap", "histamine diet",
    "elimination diet protocol", "food sensitivity testing",
    "anti inflammatory diet", "mediterranean diet",
    "dash diet", "mind diet", "blue zones diet",
    "longevity diet", "caloric restriction", "calorie restriction",
    "flexible dieting", "iifym", "if it fits your macros",
    "reverse dieting", "metabolic adaptation", "diet breaks",
    "refeed days", "carb cycling", "targeted keto",
    "cyclical ketogenic", "fat adapted athlete",
    "keto athlete", "endurance keto", "keto for women",
    "keto for men", "therapeutic keto", "keto for cancer",
    "ketosis", "blood ketones", "glucose ketone index",
    "ozempic", "glp1", "weight loss medication",
    "bariatric surgery", "gastric sleeve", "post bariatric",
    "intuitive eating community", "anti diet culture",
    "eating disorder recovery", "orthorexia recovery",
    "binge eat recovery", "restrictive eating",
    "sports dietitian", "sports nutrition community",
    "race day nutrition", "pre workout meal", "post workout meal",

    // ===== BIOHACKING DEEP =====
    "biohacker", "quantified self", "self experimentation",
    "wearable health", "continuous glucose", "cgm diet",
    "heart rate variability", "hrv training", "hrv lifestyle",
    "sleep tracker", "oura ring community", "whoop community",
    "eight sleep", "sleep environment", "sleep coaching",
    "circadian rhythm reset", "light therapy", "dawn simulator",
    "cold therapy", "cold water immersion", "ice bath",
    "contrast therapy", "hot cold protocol",
    "hyperbaric chamber", "hbot therapy", "altitude training",
    "oxygen therapy", "pulsed electromagnetic", "pemf",
    "infrared light", "photobiomodulation", "red light panel",
    "grounding practice", "earthing", "barefoot outdoor",
    "emf mitigation", "blue light glasses",
    "brain training", "neurofeedback", "meditation technology",
    "breathwork techniques", "wim hof method", "box breathing",
    "pranic breathing", "holotropic breathing", "rebirthing breath",
    "peptide community", "peptide therapy", "bpc 157",
    "nad iv", "ozone sauna", "hydrogen therapy",
    "methylene blue", "nicotinamide riboside", "rapamycin",
    "hormone testing", "dutch test", "salivary cortisol",
    "microbiome testing", "stool testing", "gut mapping",
    "nutrigenomics", "dna diet", "personalized nutrition",
    "functional lab testing", "root cause medicine",

    // ===== MENTAL HEALTH DEEP =====
    "therapy community", "online therapy", "peer support",
    "depression support", "bipolar support", "schizophrenia",
    "borderline personality", "bpd", "narcissistic abuse",
    "emotional abuse recovery", "domestic violence recovery",
    "sexual trauma recovery", "complex ptsd", "cptsd healing",
    "childhood trauma", "adverse childhood experiences",
    "inner child healing", "reparenting yourself",
    "attachment healing", "anxious attachment", "avoidant attachment",
    "secure attachment", "relationship patterns",
    "emdr therapy", "somatic therapy", "ifs",
    "internal family systems", "parts work", "ego states",
    "hakomi", "sensorimotor", "trauma sensitive yoga",
    "mindful self compassion", "self compassion practices",
    "radical acceptance", "dbt skills", "dbt community",
    "cbt skills", "cognitive distortions", "thought records",
    "act therapy", "acceptance commitment", "psychological flexibility",
    "schema therapy", "life trap patterns",
    "men mental health", "men therapy", "men circles",
    "grief group", "loss group", "bereavement support",
    "addiction recovery", "sobriety community", "aa community",
    "na community", "smart recovery", "harm reduction",
    "alcohol free lifestyle", "sober curious", "dry january",
    "quit drinking", "quit smoking", "nicotine free",

    // ===== SPIRITUALITY DEEP =====
    "non dual awareness", "advaita vedanta", "neo advaita",
    "jnana yoga", "bhakti yoga", "karma yoga", "raja yoga",
    "kundalini awakening", "kundalini rising", "kundalini kriyas",
    "tantric practice", "tantric yoga", "sacred sexuality",
    "dakini", "divine feminine rising", "feminine embodiment",
    "masculine embodiment", "king warrior magician lover",
    "shadow integration", "jungian psychology", "archetypal",
    "depth psychology", "transpersonal psychology",
    "integral spirituality", "wilber", "spiral dynamics",
    "enneagram community", "enneagram type", "enneagram coach",
    "myers briggs community", "mbti", "infj community",
    "personality types", "big five personality",
    "gene keys community", "gene keys activation",
    "human design reader", "human design coach",
    "human design type", "manifestor", "generator", "projector",
    "reflector", "manifesting generator",
    "astrology reading", "natal chart", "synastry",
    "composite chart", "vedic astrology", "jyotish",
    "western astrology", "evolutionary astrology",
    "tarot reading", "tarot coaching", "tarot business",
    "oracle cards", "angel cards", "lenormand",
    "numerology reading", "life path numbers", "master numbers",
    "channeling", "channeled messages", "mediumship",
    "psychic development", "clairvoyance training",
    "energy sensitives", "empaths community",
    "highly sensitive person", "hsp community",
    "shamanic healing", "shamanic journey", "drumming circle",
    "plant ceremony", "cacao ceremony", "medicine wheel",
    "ayahuasca integration", "psilocybin integration",
    "iboga", "ketamine therapy", "psychedelic integration",
    "microdosing community", "microdosing protocol",
    "spiritual bypassing", "grounded spirituality",
    "earth based spirituality", "paganism", "wicca", "druidry",
    "goddess spirituality", "sacred feminine", "divine masculine",
    "norse paganism", "asatru", "heathenry",
    "ceremonial magic", "hermeticism", "qabalah",
    "rosicrucianism", "theosophy", "anthroposophy",
    "gnostic community", "esoteric community",
    "near death experience", "nde community",
    "past life regression", "akashic records reading",
    "timeline jumping", "quantum healing", "hypnosis",
    "hypnotherapy practice", "nlp practitioner",
    "timeline therapy", "parts integration",

    // ===== RELATIONSHIPS DEEP =====
    "relationship coach", "couples coaching", "premarital",
    "marriage enrichment", "gottman method", "imago therapy",
    "emotionally focused therapy", "eft couples",
    "conscious relationship", "conscious partnership",
    "polyamory community", "ethical non monogamy", "enm",
    "open relationship", "relationship anarchy",
    "attachment style", "attachment theory community",
    "love languages", "five love languages",
    "dating after divorce", "dating after 40", "dating after 50",
    "online dating tips", "dating apps strategy",
    "tinder", "hinge", "bumble strategy", "dating profile",
    "shy dating", "introvert dating", "social skills dating",
    "confidence with women", "confidence with men",
    "dating as a single mom", "dating as a single dad",
    "widow dating", "widow support",
    "sex ed adults", "intimacy coaching", "pleasure coaching",
    "tantra couples", "sacred union",
    "co dependency recovery", "people pleasing recovery",
    "healthy boundaries", "setting limits",
    "family estrangement", "no contact recovery",
    "toxic family", "narcissist recovery",
    "divorce support", "divorce coaching", "divorce community",
    "separation coaching", "mediation community",
    "blended family support", "step parenting",
    "co parenting communication", "parallel parenting",

    // ===== PARENTING DEEP =====
    "gentle parenting community", "respectful parenting",
    "positive parenting", "authoritative parenting",
    "attachment parenting", "babywearing", "extended breastfeeding",
    "baby led weaning", "sleep training debate",
    "co sleeping", "family bed", "room sharing",
    "natural birth", "home birth", "midwife", "doula community",
    "unmedicated birth", "birth preparation", "birth plan",
    "postpartum support", "postpartum depression", "ppd",
    "postpartum anxiety", "maternal mental health",
    "infertility support", "ivf community", "iui",
    "donor egg", "donor sperm", "surrogacy",
    "miscarriage support", "pregnancy after loss", "rainbow baby",
    "adoption community", "transracial adoption",
    "foster parent community", "respite care",
    "special needs parent", "autism parent community",
    "adhd parent", "sensory processing community",
    "down syndrome", "cerebral palsy family",
    "ehlers danlos", "rare disease family",
    "medically complex child", "vent dependent",
    "homeschool styles", "classical homeschool", "charlotte mason",
    "unschooling lifestyle", "democratic school",
    "roadschooling", "worldschooling", "travel homeschool",
    "eclectic homeschool", "online school", "micro school",
    "nature based education", "nature school", "forest school",
    "montessori at home", "waldorf inspired",
    "toddler activities", "preschool at home",
    "reading with kids", "kids literacy",
    "stem for kids", "coding for kids",
    "raising boys", "raising girls", "raising teens",
    "teen mental health", "teen anxiety", "teen depression",
    "screen time", "tech free parenting",
    "family rhythm", "family meeting",
    "chores for kids", "allowance", "financial literacy kids",
    "travel with kids", "traveling family", "family adventure",
    "large family", "big family life", "quiverfull",
    "minimalist family", "intentional family",
    "grandparent role", "grandparenting",

    // ===== CREATIVE ARTS DEEP =====
    "figure drawing", "life drawing", "portrait drawing",
    "gesture drawing", "anatomy for artists", "figure sculpting",
    "portrait painting", "plein air painting", "landscape painting",
    "still life painting", "abstract painting", "experimental art",
    "encaustic painting", "resin art", "fluid art",
    "alcohol ink", "acrylic pour", "paint pouring",
    "oil pastel", "colored pencil", "graphite drawing",
    "charcoal drawing", "ink illustration", "brush pen",
    "procreate beginner", "digital painting tutorial",
    "pixel art community", "sprite art", "game asset",
    "character illustration", "childrens book illustration",
    "editorial illustration", "book cover design",
    "album art", "poster design", "print design",
    "zine making", "self publishing zine", "risograph",
    "linocut printing", "screen printing process",
    "cyanotype", "gum bichromate", "alternative process",
    "darkroom photography", "film developing",
    "pinhole camera", "medium format film",
    "large format photography", "view camera",
    "night photography", "milky way photography",
    "aurora photography", "lightning photography",
    "macro photography", "focus stacking",
    "high speed photography", "underwater photography",
    "infrared photography", "black white photography",
    "fine art photography", "conceptual photography",
    "documentary photography", "street photography community",
    "photojournalism", "conflict photography",
    "sports photography", "wildlife photography",
    "bird photography", "nature photography",
    "studio photography", "flash photography", "lighting setup",
    "fashion photography community", "editorial photography",
    "commercial photography", "advertising photography",
    "architecture photography", "interior photography",
    "real estate photography tips", "food photography styling",
    "prop styling", "art direction",
    "pottery wheel", "hand building", "ceramic glazing",
    "raku firing", "pit firing", "wood firing, soda firing",
    "porcelain", "stoneware", "earthenware",
    "glass blowing", "lampwork beads", "stained glass",
    "mosaic art", "tile art", "tesserae",
    "metal casting", "lost wax", "bronze casting",
    "blacksmithing", "bladesmithing", "knife making",
    "forging", "damascus steel", "pattern welding",
    "leather working", "leather craft", "saddle making",
    "bookbinding", "letterpress", "hand papermaking",
    "basket weaving", "willow weaving", "coiling",
    "macrame", "fiber arts", "weaving",
    "tapestry weaving", "floor loom", "rigid heddle",
    "natural dyeing", "indigo dyeing", "eco printing",
    "botanical dyeing", "bundle dyeing",
    "rug hooking", "rug making", "tufting",
    "needlework", "cross stitch patterns", "blackwork",
    "goldwork embroidery", "crewel embroidery",
    "swedish weaving", "hardanger", "smocking",
    "quilt patterns", "modern quilting", "art quilt",
    "whole cloth quilt", "hand quilt",
    "hand knitting", "machine knitting",
    "continental knitting", "colorwork knitting",
    "fair isle", "stranded colorwork", "intarsia",
    "lace knitting", "sock knitting", "brioche",
    "hand spinning", "drop spindle", "spinning wheel",
    "felting", "wet felting", "needle felting",
    "nuno felting", "wool painting",
    "toy making", "doll making", "teddy bear",
    "puppet making", "marionette",
    "origami", "paper folding", "modular origami",
    "kirigami", "pop up book", "paper sculpture",
    "paper mache", "decoupage",

    // ===== MUSIC DEEP EXPANSION =====
    "guitar beginner", "guitar fingerpicking", "guitar chords",
    "acoustic guitar", "electric guitar", "bass guitar",
    "classical guitar", "flamenco guitar", "slide guitar",
    "lap steel", "pedal steel", "dobro",
    "ukulele", "banjo", "mandolin", "bouzouki",
    "harp", "hammered dulcimer", "autoharp",
    "piano beginner", "piano intermediate", "advanced piano",
    "classical piano", "jazz piano", "gospel piano",
    "blues piano", "ragtime piano", "boogie woogie",
    "organ", "hammond organ", "church organ",
    "accordion", "concertina", "melodeon",
    "violin beginner", "violin technique", "fiddle",
    "celtic fiddle", "old time fiddle", "bluegrass fiddle",
    "viola", "cello", "double bass",
    "trumpet", "french horn", "trombone", "euphonium",
    "tuba", "flugelhorn", "cornet",
    "saxophone", "clarinet", "flute", "oboe", "bassoon",
    "recorder", "tin whistle", "native flute",
    "didgeridoo", "kalimba", "steel drum",
    "hand pan", "hang drum", "tongue drum",
    "djembe", "conga", "bongo", "cajon",
    "drum kit beginner", "drum technique", "jazz drumming",
    "latin percussion", "afro cuban drumming",
    "electronic drum pad", "drum machine", "mpc",
    "music theory beginner", "circle of fifths", "modes",
    "ear training", "sight reading", "improvisation",
    "jazz improvisation", "blues improvisation",
    "chord melody", "solo guitar arrangement",
    "band formation", "musician community", "open mic",
    "busking", "street music", "performance anxiety",
    "recording at home", "home recording", "daw",
    "reaper", "garageband", "cubase", "live performance",
    "stage performance", "music career",
    "music licensing tips", "sync placement",
    "spotify playlist pitching", "music promotion organic",
    "independent artist", "indie musician",
    "composer community", "film scoring community",
    "trailer music", "library music",
    "choir community", "choral singing", "a cappella",
    "barbershop quartet", "harmony singing",
    "voice actor", "singing teacher", "vocal coach",
    "speech language", "voice therapy",

    // ===== FOOD & COOKING DEEP =====
    "knife skills", "knife sharpening", "chef knife",
    "butchery", "whole animal butchery", "charcuterie",
    "curing meats", "dry curing", "wet curing",
    "smoking meats", "bbq competition", "competition bbq",
    "brisket", "pulled pork", "ribs", "burnt ends",
    "pitmaster", "offset smoker", "ceramic kamado",
    "pellet grill", "santa maria bbq",
    "grilling tips", "live fire cooking",
    "fermented foods", "lacto fermentation", "wild fermentation",
    "kimchi making", "sauerkraut", "miso making",
    "tempeh making", "natto making",
    "cheese making", "home cheese", "raw milk cheese",
    "bread baking", "sourdough starter", "sourdough community",
    "artisan bread", "enriched dough", "croissant making",
    "pasta making", "fresh pasta", "laminated dough",
    "pizza making", "neapolitan pizza", "wood fired pizza",
    "pizza dough", "fermented pizza",
    "cake decorating community", "sugar flowers", "fondant",
    "buttercream art", "cake design", "wedding cakes",
    "chocolate tempering", "bonbons", "chocolate work",
    "sugar work", "pulled sugar", "spun sugar",
    "ice cream making", "gelato making",
    "cocktail craft", "home bartending", "cocktail competition",
    "bourbon community", "whiskey tasting", "scotch whisky",
    "rum community", "mezcal", "tequila community",
    "natural wine", "biodynamic wine", "orange wine",
    "wine region", "winemaking community", "home winemaking",
    "mead making", "cider making", "vinegar making",
    "kombucha brewing", "jun tea", "water kefir",
    "beer brewing", "all grain brewing", "extract brewing",
    "lager brewing", "ipa brewing", "sour beer",
    "fermentation science", "wild yeast", "terroir",
    "food styling community", "food photography community",
    "recipe development", "food blogging community",
    "vegan chef", "raw vegan", "high carb vegan",
    "whole food plant based", "starch solution",
    "macrobiotic cooking", "traditional foods",
    "ancestral diet", "weston price", "wise traditions",
    "japanese cooking", "korean cooking", "chinese cooking",
    "thai cooking", "vietnamese cooking", "indian cooking",
    "mexican cooking", "italian cooking", "french cooking",
    "greek cooking", "mediterranean cooking", "middle eastern",
    "west african cooking", "ethiopian cooking", "north african",
    "cajun cooking", "creole cooking", "soul food",
    "southern cooking", "appalachian cooking", "native food",

    // ===== TRAVEL DEEP =====
    "budget backpacker", "hostel community", "couchsurfing",
    "workaway", "wwoof", "house sitting", "work exchange",
    "house swap", "travel hacking points", "credit card points",
    "airline miles", "hotel points", "loyalty programs",
    "travel rewards", "travel credit card",
    "slow travel", "long term travel", "perpetual travel",
    "world travel", "around the world trip", "rtw trip",
    "gap year", "sabbatical travel", "career break travel",
    "solo female travel", "solo male travel",
    "senior travel", "over 60 travel", "retirement travel",
    "family travel tips", "travel with toddlers",
    "travel with teens", "multi generational travel",
    "luxury travel tips", "five star travel",
    "cruise community", "cruise loyalty", "river cruise",
    "expedition cruise", "small ship cruise",
    "train travel", "rail pass", "trans siberian",
    "campervan europe", "campervan australia",
    "road trip usa", "road trip europe",
    "motorcycle travel", "moto travel", "adv riding",
    "bicycle touring", "cycle touring community",
    "travel photography tips", "travel content creator",
    "travel blog community", "travel instagram",
    "country counting", "un countries", "passport stamps",
    "visa tips", "travel insurance tips",
    "travel health", "vaccinations", "travel medicine",
    "expat community", "expat life",
    "expat thailand", "expat mexico", "expat portugal",
    "expat bali", "expat colombia", "expat spain",
    "expat dubai", "expat singapore", "expat japan",
    "remote worker visa", "digital nomad visa",
    "nomad tax", "perpetual traveler tax",

    // ===== PETS DEEP EXPANSION =====
    "positive dog training", "force free training",
    "clicker training", "dog agility", "dog sport",
    "schutzhund", "IPO", "dock diving",
    "flyball", "disc dog", "canine freestyle",
    "search and rescue dog", "therapy dog", "service dog",
    "dog nutrition", "raw feeding dog", "barf diet dog",
    "dog breed community", "golden retriever community",
    "labrador community", "german shepherd community",
    "border collie community", "poodle community",
    "french bulldog community", "dachshund community",
    "chihuahua community", "pitbull community",
    "rescue dog community", "shelter dog",
    "dog photography", "pet portrait photography",
    "cat behavior", "cat enrichment", "indoor cat",
    "cattery", "cat breeding", "cat showing",
    "cat rescue", "feral cat community", "tnr",
    "rabbit keeping", "rabbit behavior", "rabbit bonding",
    "guinea pig", "hamster care", "chinchilla care",
    "ferret community", "hedgehog community",
    "reptile keeping", "bearded dragon", "leopard gecko",
    "ball python", "corn snake", "chameleon keeping",
    "tortoise keeping", "turtle community",
    "parrot community", "african grey", "cockatiel",
    "conure community", "macaw community",
    "budgerigar", "lovebird", "dove community",
    "backyard chickens", "chicken keeper", "small flock",
    "duck keeping", "goat keeping", "mini goat",
    "sheep keeping", "small farm", "homestead animals",
    "beekeeping beginner", "hive management", "honey harvest",
    "natural beekeeping", "top bar hive",
    "aquarium community", "planted tank", "reef tank",
    "saltwater aquarium", "freshwater aquarium",
    "cichlid community", "betta community", "shrimp keeping",
    "koi keeping", "koi pond",

    // ===== HOBBIES & INTERESTS DEEP =====
    "board game community", "heavy euro games", "ameritrash",
    "cooperative games", "deck building", "worker placement",
    "warhammer community", "warhammer 40k", "age of sigmar",
    "miniature painting", "miniature hobby", "scale models",
    "gunpla", "model kit", "diorama building",
    "plastic models", "resin casting", "mold making",
    "prop making", "cosplay armor", "thermoforming",
    "eva foam armor", "worbla", "thermoplastics",
    "wig styling", "costume sewing", "corset making",
    "vintage sewing", "historical costume", "period costume",
    "fashion sewing", "garment construction", "patternmaking",
    "slow fashion", "mending clothes", "visible mending",
    "capsule wardrobe", "personal style",
    "thrift flipping", "upcycling clothes", "secondhand styling",
    "film photography community", "analog revival",
    "darkroom printing", "film camera collecting",
    "vintage camera", "camera restoration",
    "vinyl records", "record collecting", "audiophile",
    "hi fi community", "turntable", "vinyl pressing",
    "music listening", "album appreciation",
    "book collecting", "rare books", "antiquarian books",
    "first edition books", "book restoration",
    "comic book collecting", "graded comics",
    "sports memorabilia", "sports card grading",
    "funko pop collecting", "action figure",
    "antique collecting", "vintage collecting",
    "coin collecting", "numismatics", "error coins",
    "stamp collecting", "philately",
    "postcard collecting", "ephemera collecting",
    "vintage toy collecting", "dinky toys", "tin toy",
    "watch collecting", "vintage watch", "microbrand watch",
    "pen collecting", "fountain pen", "ink collecting",
    "stationery community", "journal community",
    "bujo community", "bullet journal", "planner community",
    "planning community", "notebooks obsession",
    "reading community", "book club online",
    "fantasy book club", "sci fi book club",
    "romance readers", "thriller readers", "mystery readers",
    "literary fiction", "nonfiction book club",
    "true crime community", "cold case community",
    "history enthusiast", "military history", "ancient history",
    "genealogy research", "family history", "ancestry research",
    "dna genealogy", "genetic genealogy",
    "language learning community", "polyglot community",
    "japanese learning", "spanish learning", "mandarin learning",
    "arabic learning", "hindi learning", "french learning",
    "german learning", "korean learning", "portuguese learning",
    "russian learning", "italian learning", "latin learning",
    "sign language learning", "asl community",
    "chess community", "chess improvement", "chess openings",
    "chess endgame", "blitz chess", "correspondence chess",
    "go game", "weiqi", "baduk",
    "bridge card game", "poker community", "poker strategy",
    "mahjong", "shogi", "xiangqi",
    "magic trick community", "close up magic", "street magic",
    "mentalism community", "card magic",
    "escape room design", "puzzle design",
    "crossword puzzle", "sudoku", "word games",
    "trivia community", "pub quiz",
    "astronomy club", "amateur astronomy",
    "telescope community", "astrophotography beginner",
    "planetary observation", "deep sky objects",
    "ham radio community", "amateur radio",
    "morse code", "hf radio", "satellite communication",
    "remote sensing", "weather station",
    "metal detecting community", "treasure hunting",
    "gold panning", "prospecting",
    "geocaching community", "adventure cache",
    "urban exploration", "urbex", "abandoned places",
    "lock picking community", "locksport",
    "parkour", "freerunning", "movement art",

    // ===== CAREER & PROFESSIONAL NICHES REAL LIFE =====
    "nurse community", "nursing support", "bedside manner",
    "travel nurse", "nurse practitioner community",
    "physician community", "doctor burnout", "medical community",
    "veterinarian community", "vet tech community",
    "teacher community", "educator support", "classroom ideas",
    "homeschool educator", "curriculum sharing",
    "social worker community", "therapist community",
    "counselor community", "private practice therapist",
    "firefighter community", "first responder",
    "police officer community", "law enforcement",
    "military community", "veterans community", "ptsd veteran",
    "military spouse", "deployment support",
    "pastor community", "church planting", "ministry leader",
    "missionary community", "youth pastor",
    "nonprofit leader", "charity founder",
    "artist community", "working artist", "art career",
    "musician community", "touring musician", "indie artist",
    "writer community", "author community", "fiction writers",
    "photographer community", "photography business",
    "chef community", "restaurant industry", "hospitality",
    "personal trainer community", "fitness professional",
    "physical therapist community", "chiropractor community",
    "acupuncturist community", "naturopath community",
    "massage therapist community", "bodywork community",
    "yoga teacher community", "pilates teacher community",
    "dance teacher community", "martial arts instructor",
    "coach community", "life coach community",
    "farmer community", "small farm community",
    "rancher community", "cattleman", "livestock keeper",
    "grower community", "market gardener",
    "tradesperson", "electrician community", "plumber community",
    "carpenter community", "builder community",
    "trucker community", "owner operator",
    "pilot community", "aviator community",
    "sailor community", "merchant marine",
    "actor community", "theater community", "performer",
    "comedian community", "comic performer",
    "speaker community", "public speaker community",
    "author community", "book writing community",
];

/**
 * Generates URL array for Skool Discovery search.
 */
export function generateStartUrls() {
    // Start with general discovery pages by category
    const urls = [
        'https://www.skool.com/discovery',
        'https://www.skool.com/discovery?c=health-&-fitness',
        'https://www.skool.com/discovery?c=personal-development',
        'https://www.skool.com/discovery?c=business',
        'https://www.skool.com/discovery?c=arts-&-crafts',
        'https://www.skool.com/discovery?c=sports',
        'https://www.skool.com/discovery?c=relationships',
        'https://www.skool.com/discovery?c=spirituality',
        'https://www.skool.com/discovery?c=education',
        'https://www.skool.com/discovery?c=finance',
        'https://www.skool.com/discovery?c=food-&-drink',
        'https://www.skool.com/discovery?c=travel',
        'https://www.skool.com/discovery?c=pets',
        'https://www.skool.com/discovery?c=hobbies',
    ];

    const seen = new Set(urls);
    for (const keyword of NICHE_KEYWORDS) {
        const encoded = encodeURIComponent(keyword).replace(/%20/g, '+');
        const url = `https://www.skool.com/discovery?q=${encoded}`;
        if (!seen.has(url)) {
            urls.push(url);
            seen.add(url);
        }
    }

    return urls;
}

export { NICHE_KEYWORDS };
